spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: America/Sao_Paulo
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,info,health
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
